### ISSUE TITLE
mwoffliner should store the alt text of maths fallback images

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#114]
If I've understood correctly, `wikipedia_en_medicine_novid_2017-07.zim` is one of the new ZIM formats produced by mwoffliner. I've noticed that it is not storing the alt text of maths fallback images -- those with `class="mwe-math-fallback-image-inline"`. Here is an example of the image code stored in the new format file, taken from the article "Wilson-Cowan model" in this ZIM:

`<img src="../I/m/77ef7f1c5b9443e5d7cf559292e5f01638217c02.svg" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -2.338ex; width:16.509ex; height:6.176ex;">`

And here is an example of a maths fallback image from the same article in `wikipedia_en_all_2016-12.zim`:

`<img class="mwe-math-fallback-image-inline tex" alt="\int_{-\infty}^{t}\alpha(t-t')[c_1 E(t')-c_2 I(t')+P(t')]dt'" src="../I/m/ac60da472819d05a3f6f39314c8ca1ef.png" id="mwHA">`

Finally, here is an image from the same article taken from the current (live) en.wikipedia.org (online):

`<img class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -2.338ex; width:42.214ex; height:6.176ex;" alt="{\displaystyle \int _{-\infty }^{t}\alpha (t-t')[c_{1}E(t')-c_{2}I(t')+P(t')]dt'}" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/3194cd1611482e86ed216634c6c9a53b1bae1ec3">`

Note that in the 2016 version ZIM and in the current live/online version, the alt field holds the original TEX string from which the fallback image is generated, but it is missing from the 2017 format ZIM. Assuming this is an mwoffliner issue, I don't think it should throw this information away, as clients may wish to use it. More generally, of course, mwoffliner should not throw away alt text for images, but I haven't tested if this is a broader issue.

**Comment by Jaifroid** [comment]
On a quick test of a couple of articles from the 60GB `wikipedia_en_all_novid_2017-07.zim`, which I've just finished downloading, the TeX strings in the alt-text of the fallback images for equations now appear to be present and correct. So either this issue has been fixed in mw-offliner, or, more likely, the issue is in the Wikimed book collection software rather than in mw-offliner. I guess we should do a few more tests before closing the issue here.

**Comment by Jaifroid** [comment]
Interesting issue in source code of article "Wilson-Cowan model" in `wikipedia_en_all_novid_2017-07.zim`. It looks like there was a failure with the maths extension server at the time of scraping for just one of the equations (NB, this is confirmed to be in the HTML stored in the ZIM, it's not an error introduced in the ZIM rendering client): 

![image](https://user-images.githubusercontent.com/4304337/30239194-f9a23cbe-954e-11e7-9ca8-ef7b0a71adbb.png)

A [search](https://www.google.co.uk/search?q=%22Math+extension+cannot+connect+to+Restbase.%22) for the error suggests some kind of timeout. If we find this happening on a few of the scraped pages with MathML, it might be worth explicitly requerying the server if that error is received.

**Comment by kelson42** [comment]
@Jaifroid Previous comment is an other problem for which I think there is not much we can do. For the rest I confirm the issue, so far I can see, the problem is still there.

**Comment by Jaifroid** [comment]
@kelson42 Yes, I agree it's a different issue.
On the main issue, to be clear, the TeX strings are *missing* from the wikimed archive, but they are *present* in the latest English Wikipedia archive, which I assume is also made with mw-offliner (it has mobile stylesheets). Not sure why they'd be missing in one but present in the other. Only difference I can think of is the software that collates/collects the medical pages...

**Comment by kelson42** [comment]
@Jaifroid So, I had a look in detail and indeed it seems this bug has been fixed recently :) Thank you for having reported it. Please reopen if you again this kind of problem in a newly generated file.
