### ISSUE TITLE
Wikivoyage landing page links crash application

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#852]
Following up on [/openzim/zimfarm/issues/257](https://github.com/openzim/zimfarm/issues/257)

Clicking on any link on this landing page will cause the application to crash on macOS, or lead to a blank page on Android. 

On Android I seem to be able to search for and access articles, but not on macOS/iOS (this was initially reported by an iOS user).

See also #794

**Comment by kelson42** [comment]
If we have a crash, this is a bug by the reader.

**Comment by kelson42** [comment]
@Popolechien Please open one ticket for one problem, I have created #157 for the crash on MacOS. The root problem (of missing article in the ZIM) has been fixed in #726.

**Comment by Jaifroid** [comment]
I just want to add that this issue probably is related to the fact that the hyperlinks on the landing page of `wikivoyage_en_all_novid_2019-06.zim` are incorrect. The landing page's URL is: 

`Wikivoyage%3AOffline_reader_Expedition/Home_page`

(note the forward slash). However, hyperlinks on the page are:

`<a title="Europe" href="Europe">Europe</a>`

That's clearly incorrect, as the href should be `../Europe`. This should have been fixed in mwoffliner https://github.com/kiwix/kiwix-js/pull/498. I'm not sure #157 should "fix" what is an error in the ZIM.

**Comment by kelson42** [comment]
@Jaifroid Thank you for insisting, this is still not working fine on MWoffliner side, really sorry for this never ending story.
